name: Publish Docker image to GHCR

on:
  push:
    branches: [ main ]           # build on every commit to main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write            # allow pushing to GHCR

    steps:
      # 1 — Checkout source
      - uses: actions/checkout@v4

      # 2 — Enable ARM emulation (Pi builds) and Buildx
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      # 3 — Log in to GitHub Container Registry
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4 — Generate smart tags & labels
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/chartres/zivyobraz-departures
          # Adds:           v1.2.3, v1.2, v1, sha-<short>, latest (only on main)
          # Plus OCI labels like org.opencontainers.image.source

      # 5 — Build once, push a multi-arch manifest (ARMv7, ARM64, AMD64)
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm/v7,linux/arm64,linux/amd64
          tags:   ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
